name: Generate contributions line chart

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate chart using GITHUB_TOKEN
        env:
          GH_USERNAME: Andresflorezdev
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node .github/scripts/generate-contributions-line.mjs

      - name: Commit & push
        uses: EndBug/add-and-commit@v9
        with:
          add: "assets/contributions-line.svg"
          message: "chore: update contributions line chart"
          default_author: github_actions